version: '3.8'

services:
  postgres:
    image: postgres:17.7
    container_name: vuenm-postgres-db
    environment:
      POSTGRES_USER: vuenm
      POSTGRES_PASSWORD: vuenm
      POSTGRES_DB: vuenm
    ports:
      - "5400:5432"
    volumes:
      - vuenm_postgres_data:/var/lib/postgresql/data 
    networks:
      - vuenm
  
volumes:
  vuenm_postgres_data:

networks:
  vuenm:
    driver: bridge